on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install and build Node.js app
        run: |
          npm install
          npm run build
        working-directory: ./temp

      - name: Print environment variables
        run: env

